use_frameworks!

target 'CardanMessage_Example' do
  pod 'CardanMessage', :path => '../'
  pod 'CTMediator'

  target 'CardanMessage_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
